require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

$FirebaseSDKVersion = '7.0.0'

target 'Nexton' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'IQKeyboardManager' #iOS8 and later

  pod 'react-native-simple-toast', :path => '../node_modules/react-native-simple-toast'


  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  

  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'
  
  pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'
  
  target 'NextonTests' do
    inherit! :complete
    # Pods for testing

    
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'Nexton-tvOS' do
  # Pods for Nexton-tvOS

  target 'Nexton-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
